JOB_TITLE_SEARCH_WORDS = [
    'Software',
    'Systems',
    'Project',
    'Principal',
    'Applications',
    'Cloud',
    'Solution',
    'Architect',
    'Algorithm',
    'Test',
    'IT',
    'IOS',
    'UI-UX',
    'Designer'
]

SELECTED_COLS_ID = [
    'benefits.highlights',  # Benefits highlights table id
    'reviews',  # Reviews table id
    'salary.salaries',  # Salaries table id
]

SELECTED_COLS_MAIN = [
    'job.description',  # Job description TODO: calculate word count and TF-IDF on most 10~20 frequent words
    'header.sponsored',  # Boolean Whether the job is sponsored
    'map.location',  # Job location
    'gaTrackerData.empSize',  # Categorical Company size
    'gaTrackerData.industry',  # Categorical Company Industry
    'overview.type',  # Company type
    'benefits.benefitRatingDecimal',  # Num Employee rating on company benefits
    'rating.ceoApproval',  # CEO approval rating
    'rating.recommendToFriend',  # Recommend to friend rating
    'rating.starRating',  # Overall rating
]

SELECTED_COLS_BENI = [
    'id',
    'benefits.highlights.val.name'  # Employee benefits
]

SELECTED_COLS_REVIEW = [
    'id',
    'reviews.val.cons',  # Employee reviews: cons
    'reviews.val.pros',  # Employee reviews: pros
]

SELECTED_COLS_SALARY = [
    'id',
    'salary.salaries.val.salaryPercentileMap.payPercentile10',
    'salary.salaries.val.salaryPercentileMap.payPercentile90',
    'salary.salaries.val.payPeriod',
    'salary.salaries.val.jobTitle'
]

OUTLIER_COLS_MAIN = [
    'benefits.benefitRatingDecimal',
    'rating.ceoApproval',
    'rating.recommendToFriend',
    'rating.starRating'
]

DATA_FILE_PATHS = [
    '../data/glassdoor.csv',
    '../data/glassdoor_benefits_highlights.csv',
    '../data/glassdoor_reviews.csv',
    '../data/glassdoor_salary_salaries.csv'
]

CLEAN_DATA_PATH = '../data/glassdoor_clean_data.csv'

US_STATES = [
    'AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME',
    'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA',
    'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'
]

TECH_STACK = [
    "java",
    "python",
    "javascript",
    "sql",
    "c++",
    "aws",
    "amazon web services",
    "git",
    "docker",
    "kubernetes",
    "react",
    "node.js",
    "html",
    "css",
    "agile",
    "linux",
    "devops",
    "restful",
    ".net",
    "c#",
    "php",
    "ruby",
    "apache",
    "spark",
    "typescript",
    "flask",
    "django",
    "tensorflow",
    "spring",
    "azure",
    "redux",
    "vue.js",
    "angular",
    "bash",
    "mongodb",
    "hadoop",
    "pytorch",
    "react",
    "firebase",
    "unity",
    "jenkins",
    "oauth",
    "mysql",
    "postgresql",
    "apache kafka",
    "ansible",
    "elasticsearch",
    "golang",
    "ionic",
    "swift",
    "objective-c",
    "kotlin",
    "xamarin",
    "express.js",
    "graphql",
    "selenium",
    "jira",
    "apache cassandra",
    "rabbitmq",
    "chef",
    "puppet"
]

CLEAN_DATA_COLUMNS = [
    'header.sponsored',
    'map.location',
    'benefits.benefitRatingDecimal',
    'rating.ceoApproval',
    'rating.recommendToFriend',
    'rating.starRating',
    'description_java_count',
    'description_python_count',
    'description_javascript_count',
    'description_sql_count',
    'description_c++_count',
    'description_aws_count',
    'description_amazon web services_count',
    'description_git_count',
    'description_docker_count',
    'description_kubernetes_count',
    'description_react_count',
    'description_node.js_count',
    'description_html_count',
    'description_css_count',
    'description_agile_count',
    'description_linux_count',
    'description_devops_count',
    'description_restful_count',
    'description_.net_count',
    'description_c#_count',
    'description_php_count',
    'description_ruby_count',
    'description_apache_count',
    'description_spark_count',
    'description_typescript_count',
    'description_flask_count',
    'description_django_count',
    'description_tensorflow_count',
    'description_spring_count',
    'description_azure_count',
    'description_redux_count',
    'description_vue.js_count',
    'description_angular_count',
    'description_bash_count',
    'description_mongodb_count',
    'description_hadoop_count',
    'description_pytorch_count',
    'description_firebase_count',
    'description_unity_count',
    'description_jenkins_count',
    'description_oauth_count',
    'description_mysql_count',
    'description_postgresql_count',
    'description_apache kafka_count',
    'description_ansible_count',
    'description_elasticsearch_count',
    'description_golang_count',
    'description_ionic_count',
    'description_swift_count',
    'description_objective-c_count',
    'description_kotlin_count',
    'description_xamarin_count',
    'description_express.js_count',
    'description_graphql_count',
    'description_selenium_count',
    'description_jira_count',
    'description_apache cassandra_count',
    'description_rabbitmq_count',
    'description_chef_count',
    'description_puppet_count',
    'gaTrackerData.empSize_-1-0',
    'gaTrackerData.empSize_1-50',
    'gaTrackerData.empSize_10000--1',
    'gaTrackerData.empSize_1001-5000',
    'gaTrackerData.empSize_201-500',
    'gaTrackerData.empSize_5001-10000',
    'gaTrackerData.empSize_501-1000',
    'gaTrackerData.empSize_51-200',
    'gaTrackerData.industry_Accounting',
    'gaTrackerData.industry_Advertising & Marketing',
    'gaTrackerData.industry_Aerospace & Defense',
    'gaTrackerData.industry_Airlines',
    'gaTrackerData.industry_Architectural & Engineering Services',
    'gaTrackerData.industry_Auctions & Galleries',
    'gaTrackerData.industry_Banks & Credit Unions',
    'gaTrackerData.industry_Beauty & Personal Accessories Stores',
    'gaTrackerData.industry_Biotech & Pharmaceuticals',
    'gaTrackerData.industry_Brokerage Services',
    'gaTrackerData.industry_Bus Transportation Services',
    'gaTrackerData.industry_Cable, Internet & Telephone Providers',
    'gaTrackerData.industry_Car Rental',
    'gaTrackerData.industry_Casual Restaurants',
    'gaTrackerData.industry_Catering & Food Service Contractors',
    'gaTrackerData.industry_Charter Air Travel',
    'gaTrackerData.industry_Chemical Manufacturing',
    'gaTrackerData.industry_Colleges & Universities',
    'gaTrackerData.industry_Commercial Equipment Rental',
    'gaTrackerData.industry_Commercial Equipment Repair & Maintenance',
    'gaTrackerData.industry_Computer Hardware & Software',
    'gaTrackerData.industry_Construction',
    'gaTrackerData.industry_Consulting',
    'gaTrackerData.industry_Consumer Electronics & Appliances Stores',
    'gaTrackerData.industry_Consumer Product Rental',
    'gaTrackerData.industry_Consumer Products Manufacturing',
    'gaTrackerData.industry_Department, Clothing, & Shoe Stores',
    'gaTrackerData.industry_Drug & Health Stores gaTrackerData.industry_Education Training Services',
    'gaTrackerData.industry_Electrical & Electronic Manufacturing',
    'gaTrackerData.industry_Energy',
    'gaTrackerData.industry_Enterprise Software & Network Solutions',
    'gaTrackerData.industry_Express Delivery Services',
    'gaTrackerData.industry_Farm Support Services',
    'gaTrackerData.industry_Fast-Food & Quick-Service Restaurants',
    'gaTrackerData.industry_Federal Agencies',
    'gaTrackerData.industry_Financial Analytics & Research',
    'gaTrackerData.industry_Financial Transaction Processing',
    'gaTrackerData.industry_Food & Beverage Manufacturing',
    'gaTrackerData.industry_Food Production',
    'gaTrackerData.industry_Gambling',
    'gaTrackerData.industry_General Merchandise & Superstores',
    'gaTrackerData.industry_General Repair & Maintenance',
    'gaTrackerData.industry_Gift, Novelty & Souvenir Stores',
    'gaTrackerData.industry_Grantmaking Foundations',
    'gaTrackerData.industry_Grocery Stores & Supermarkets',
    'gaTrackerData.industry_Health Care Products Manufacturing',
    'gaTrackerData.industry_Health Care Services & Hospitals',
    'gaTrackerData.industry_Health Fundraising Organizations',
    'gaTrackerData.industry_Health, Beauty, & Fitness',
    'gaTrackerData.industry_Home Furniture & Housewares Stores',
    'gaTrackerData.industry_Hotels, Motels, & Resorts',
    'gaTrackerData.industry_IT Services',
    'gaTrackerData.industry_Industrial Manufacturing',
    'gaTrackerData.industry_Insurance Agencies & Brokerages',
    'gaTrackerData.industry_Insurance Carriers',
    'gaTrackerData.industry_Internet',
    'gaTrackerData.industry_Investment Banking & Asset Management',
    'gaTrackerData.industry_Legal',
    'gaTrackerData.industry_Lending',
    'gaTrackerData.industry_Logistics & Supply Chain',
    'gaTrackerData.industry_Media & Entertainment Retail Stores',
    'gaTrackerData.industry_Membership Organizations',
    'gaTrackerData.industry_Metal & Mineral Manufacturing',
    'gaTrackerData.industry_Mining',
    'gaTrackerData.industry_Miscellaneous Manufacturing',
    'gaTrackerData.industry_Motion Picture Production & Distribution',
    'gaTrackerData.industry_Museums, Zoos & Amusement Parks',
    'gaTrackerData.industry_Music Production & Distribution',
    'gaTrackerData.industry_News Outlet',
    'gaTrackerData.industry_Office Supply Stores',
    'gaTrackerData.industry_Oil & Gas Exploration & Production',
    'gaTrackerData.industry_Oil & Gas Services',
    'gaTrackerData.industry_Other Retail Stores',
    'gaTrackerData.industry_Publishing',
    'gaTrackerData.industry_Radio',
    'gaTrackerData.industry_Rail',
    'gaTrackerData.industry_Real Estate',
    'gaTrackerData.industry_Religious Organizations',
    'gaTrackerData.industry_Research & Development',
    'gaTrackerData.industry_Security Services',
    'gaTrackerData.industry_Shipping',
    'gaTrackerData.industry_Social Assistance',
    'gaTrackerData.industry_Sporting Goods Stores',
    'gaTrackerData.industry_Sports & Recreation',
    'gaTrackerData.industry_Staffing & Outsourcing',
    'gaTrackerData.industry_Stock Exchanges',
    'gaTrackerData.industry_TV Broadcast & Cable Networks',
    'gaTrackerData.industry_Telecommunications Manufacturing',
    'gaTrackerData.industry_Telecommunications Services',
    'gaTrackerData.industry_Transportation Equipment Manufacturing',
    'gaTrackerData.industry_Transportation Management',
    'gaTrackerData.industry_Travel Agencies',
    'gaTrackerData.industry_Upscale Restaurants',
    'gaTrackerData.industry_Utilities',
    'gaTrackerData.industry_Vehicle Dealers',
    'gaTrackerData.industry_Venture Capital & Private Equity',
    'gaTrackerData.industry_Veterinary Services',
    'gaTrackerData.industry_Video Games',
    'gaTrackerData.industry_Wholesale',
    'overview.type_Company - Private',
    'overview.type_Company - Public',
    'overview.type_Other',
    'benefits.highlights.val.name_Annual Leave',
    'benefits.highlights.val.name_Bereavement Leave',
    'benefits.highlights.val.name_Bike to Work Scheme',
    'benefits.highlights.val.name_Childcare Vouchers',
    'benefits.highlights.val.name_Critical Illness Cover',
    'benefits.highlights.val.name_Death in Service',
    'benefits.highlights.val.name_Employee Discount',
    'benefits.highlights.val.name_Flexible Working',
    'benefits.highlights.val.name_Free Lunch or Snacks',
    'benefits.highlights.val.name_Gym Membership',
    'benefits.highlights.val.name_Health Cash Plan',
    'benefits.highlights.val.name_Health Insurance',
    'benefits.highlights.val.name_Income Protection',
    'benefits.highlights.val.name_Job Training',
    'benefits.highlights.val.name_Life Insurance',
    'benefits.highlights.val.name_Maternity & Paternity Leave',
    'benefits.highlights.val.name_Pension Plan',
    'benefits.highlights.val.name_Performance Bonus',
    'benefits.highlights.val.name_Professional Development',
    'benefits.highlights.val.name_Share Incentive Plan',
    'benefits.highlights.val.name_Sick Pay',
    'benefits.highlights.val.name_Stock Options',
    'benefits.highlights.val.name_Unpaid Extended Leave',
    'benefits.highlights.val.name_Work From Home',
    'pro_sentiment',
    'con_sentiment',
    'jobLevel',
    'jobCategory_Development',
    'jobCategory_Other',
    'jobCategory_Solution',
    'jobCategory_Support',
    'jobCategory_System',
    'jobCategory_Test'
]
