def transfer_strings():
    industries = [
        "Accounting",
        "Advertising & Marketing",
        "Aerospace & Defense",
        "Airlines",
        "Architectural & Engineering Services",
        "Auctions & Galleries",
        "Banks & Credit Unions",
        "Beauty & Personal Accessories Stores",
        "Biotech & Pharmaceuticals",
        "Brokerage Services",
        "Bus Transportation Services",
        "Cable, Internet & Telephone Providers",
        "Car Rental",
        "Casual Restaurants",
        "Catering & Food Service Contractors",
        "Charter Air Travel",
        "Chemical Manufacturing",
        "Colleges & Universities",
        "Commercial Equipment Rental",
        "Commercial Equipment Repair & Maintenance",
        "Computer Hardware & Software",
        "Construction",
        "Consulting",
        "Consumer Electronics & Appliances Stores",
        "Consumer Product Rental",
        "Consumer Products Manufacturing",
        "Department, Clothing, & Shoe Stores",
        "Drug & Health Stores",
        "Education Training Services",
        "Electrical & Electronic Manufacturing",
        "Energy",
        "Enterprise Software & Network Solutions",
        "Express Delivery Services",
        "Farm Support Services",
        "Fast-Food & Quick-Service Restaurants",
        "Federal Agencies",
        "Financial Analytics & Research",
        "Financial Transaction Processing",
        "Food & Beverage Manufacturing",
        "Food Production",
        "Gambling",
        "General Merchandise & Superstores",
        "General Repair & Maintenance",
        "Gift, Novelty & Souvenir Stores",
        "Grantmaking Foundations",
        "Grocery Stores & Supermarkets",
        "Health Care Products Manufacturing",
        "Health Care Services & Hospitals",
        "Health Fundraising Organizations",
        "Health, Beauty, & Fitness",
        "Home Furniture & Housewares Stores",
        "Hotels, Motels, & Resorts",
        "IT Services",
        "Industrial Manufacturing",
        "Insurance Agencies & Brokerages",
        "Insurance Carriers",
        "Internet",
        "Investment Banking & Asset Management",
        "Legal",
        "Lending",
        "Logistics & Supply Chain",
        "Media & Entertainment Retail Stores",
        "Membership Organizations",
        "Metal & Mineral Manufacturing",
        "Mining",
        "Miscellaneous Manufacturing",
        "Motion Picture Production & Distribution",
        "Museums, Zoos & Amusement Parks",
        "Music Production & Distribution",
        "News Outlet",
        "Office Supply Stores",
        "Oil & Gas Exploration & Production",
        "Oil & Gas Services",
        "Other Retail Stores",
        "Publishing",
        "Radio",
        "Rail",
        "Real Estate",
        "Religious Organizations",
        "Research & Development",
        "Security Services",
        "Shipping",
        "Social Assistance",
        "Sporting Goods Stores",
        "Sports & Recreation",
        "Staffing & Outsourcing",
        "Stock Exchanges",
        "TV Broadcast & Cable Networks",
        "Telecommunications Manufacturing",
        "Telecommunications Services",
        "Transportation Equipment Manufacturing",
        "Transportation Management",
        "Travel Agencies",
        "Upscale Restaurants",
        "Utilities",
        "Vehicle Dealers",
        "Venture Capital & Private Equity",
        "Veterinary Services",
        "Video Games",
        "Wholesale"
    ]

    benefits = [
        "Annual Leave",
        "Bereavement Leave",
        "Bike to Work Scheme",
        "Childcare Vouchers",
        "Critical Illness Cover",
        "Death in Service",
        "Employee Discount",
        "Flexible Working",
        "Free Lunch or Snacks",
        "Gym Membership",
        "Health Cash Plan",
        "Health Insurance",
        "Income Protection",
        "Job Training",
        "Life Insurance",
        "Maternity & Paternity Leave",
        "Pension Plan",
        "Performance Bonus",
        "Professional Development",
        "Share Incentive Plan",
        "Sick Pay",
        "Stock Options",
        "Unpaid Extended Leave",
        "Work From Home"
    ]
    options = ""
    # for industry in industries:
    #     industry_option = '<option value="{}">{}</option>'.format(industry, industry)
    #     options += industry_option + "\n"
    for benefit in benefits:
        benefit_option = '<option value="{}">{}</option>'.format(benefit, benefit)
        options += benefit_option + "\n"
    return options


if __name__ == '__main__':
    print(transfer_strings())
